apiVersion: apps/v1
kind: Deployment
metadata:
  name: cargotracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cargotracker
  template:
    metadata:
      labels:
        app: cargotracker
    spec:
      containers:
        - name: cargotracker
          image: smollcoco/cargotracker-app:latest
          ports:
            - containerPort: 8080
