apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cargotracker-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: cargotracker.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cargotracker-service
            port:
              number: 8080
